### ISSUE TITLE
Suggestions for improvements

### ISSUE THREAD

**Issue by tomvannuenen** [dlab-berkeley/introduction-to-pandas#19]
1. `unemployment_rate` is a bit of a weird name (as it’s not actual unemployment rates but a DF with null proportions for unemployment rates
2. `unemployment_rate_missing = unemployment[unemployment['unemployment_rate'].isnull()]` -> no need for double subset
3. Using `round()` in Manipulating Columns needs to be explained. If we don’t use it, we will not get to a full integer and then calling int() will truncate. Compare `((unemployment['year_month'] - unemployment['year']) * 100).astype(int)` and  `((unemployment['year_month'] - unemployment['year']) * 100).round(0).astype(int)` - first starts at 0, second starts at 1
4. The challenge 12 solution seems too complex. We can just do `.dropna` on our newly created `ps` column?

**Comment by pssachdeva** [comment]
Could you split these up into separate issues? That way we can close them one at a time.
